### ISSUE TITLE
Don't reduce to `import std;`

### ISSUE THREAD

**Issue by WebFreak001** [CyberShadow/DustMite#79] opened 2023-05-01 22:18 UTC
almost always when I try to use dustmite to find some kind of compiler issue it eventually reduces down std import to only `import std;`, bringing in many problems:

- sometimes the file is literally just an import, making my previously reduced code now even more complex than what I started with, since it suddenly includes much more of phobos
- this significantly slows down compilation time, and with that the time every step takes

I used to provide a regex to dustmite to not reduce that but I can't find it in my history anymore.

Since this happens almost every time I would really like to see dustmite to automatically include some kind of prevention to not reduce `import std.x;` to `import std;`

Bonus points if it's still able to remove `import std.x;` fully though, since that's something that broke with my regex hack.

**Comment by CyberShadow** [comment] 2023-05-01 22:20
Duplicate of #78 but thanks for reminding me about this problem.

**Closed by CyberShadow** 2023-05-01 22:20 UTC

**Comment by CyberShadow** [comment] 2023-05-02 07:40
BTW, the solution I'm thinking of for this problem is to just not reduce fully-qualified module names, i.e. `std.stdio` in an import should always be parsed as a single unbreakable word.

**Comment by CyberShadow** [comment] 2023-05-02 20:41
As of d0af4a5111f69df1d0077a271314e0fc0b8c6f99, Dustmite should no longer reduce module names in import statements.
